name: Print Workflow Environment Variable with Current Time
on:
  workflow_dispatch:
    inputs:
      tenant:
        type: choice
        required: true
        description: 'The tenant to update'
        options:
        - 'tenantA'

jobs:
  print-current-time:
    name: PrintCurrentTime
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set_name.outputs.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Current Time
        run: |
          echo "The current time for tenant ${{ inputs.tenant }} is: $(date)"

      - id: set_name
        run: |
          echo "name=${{ inputs.tenant }}_$(date +%Y%m%d%H%M%S)" > "$GITHUB_OUTPUT"

  create-bundle:
    name: CreateBundle
    needs: print-current-time
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Print Tenant Name
        run: echo "${{ needs.print-current-time.outputs.env_name }}"


      - name: Create Bundle
        run: |
          python ./create.py ${{ inputs.tenant }} ${{ needs.print-current-time.outputs.env_name }}
